version: '3.8'

services:
  postgres:
    image: postgres:16-alpine
    container_name: go-crud-postgres
    environment:
      POSTGRES_USER: ${DB_USER:-postgres}
      POSTGRES_PASSWORD: ${DB_PASSWORD:-postgres}
      POSTGRES_DB: ${DB_NAME:-go_crud}
    ports:
      - "${DB_PORT:-5432}:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER:-postgres} -d ${DB_NAME:-go_crud}"]
      interval: 10s
      timeout: 5s
      retries: 5

  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: go-crud-api
    ports:
      - "${HTTP_PORT:-8080}:8080"
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      - DB_HOST=postgres
      - DB_PORT=${DB_PORT:-5432}
      - DB_USER=${DB_USER:-postgres}
      - DB_PASSWORD=${DB_PASSWORD:-postgres}
      - DB_NAME=${DB_NAME:-go_crud}
      - JWT_SECRET=${JWT_SECRET:-super-secret-change-me}
      - HTTP_PORT=${HTTP_PORT:-8080}
      - APP_ENV=${APP_ENV:-dev}

volumes:
  postgres_data:
    driver: local
