name: Go CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: '1.24.5' # Use a versão do Go que você está usando

    - name: Clean Go module cache
      run: go clean -modcache

    - name: Download Go modules
      run: go mod download

    - name: Run tests
      run: go test ./... -v

    - name: Tidy Go modules
      run: go mod tidy

    - name: Run tests
      run: go test ./... -v

    - name: Install golangci-lint
      run: go install github.com/golangci/golangci-lint/cmd/golangci-lint@v1.57.2

    - name: Run golangci-lint manually
      run: |
        golangci-lint run ./... --verbose --tests=true

    - name: Build
      run: go build -v ./cmd/api
