name: Go CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: '1.24.5'
        cache: false

    - name: Install Dependencies
      run: |
        go mod tidy
        go mod vendor
    
    - name: Run tests
      run: go test -mod=vendor ./... -v

    - name: Install and run golangci-lint
      # A forma correta é usar a variável de ambiente GOFLAGS
      # para que o linter e as ferramentas Go que ele chama usem o modo vendor.
      run: golangci-lint run
      env:
        GOFLAGS: -mod=vendor

    - name: Build
      run: go build -mod=vendor -v ./cmd/api