name: Go CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: '1.24.x'
        cache: true

    - name: Install Dependencies
      run: |
        go mod tidy
        go mod vendor
        
    - name: Debug Go
      run: go env
    
    - name: Run tests
      run: go test -mod=vendor ./... -v

    - name: Install and run golangci-lint
      run: |
        go install github.com/golangci/golangci-lint/cmd/golangci-lint@latest
        GOFLAGS=-mod=vendor golangci-lint run

    - name: Build
      run: go build -mod=vendor -v ./cmd/api